// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entites.Table
{
    public partial class events
    {
        public int id { get; set; }
        public int? match_number { get; set; }
        public int? regional_team_a_id { get; set; }
        public int? team_a_final_score { get; set; }
        public int? regional_team_b_id { get; set; }
        public int? team_b_final_score { get; set; }
        public int? sport_sub_category_id { get; set; }
        public int? venue_id { get; set; }
        public string event_title { get; set; }
        public DateTime? schedule { get; set; }
        public bool? on_stream { get; set; }
        public string stream_url { get; set; }
        public bool? is_finished { get; set; }
        public byte[] attachments { get; set; }
        public virtual regional_teams regional_team_a { get; set; }
        public virtual regional_teams regional_team_b { get; set; }
        public virtual sport_sub_categories sport_sub_category { get; set; }
        public virtual venues venue { get; set; }
    }
}
