// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entites.Table
{
    public partial class sports_categories
    {
        public int id { get; set; }
        public string category { get; set; }
        public virtual ICollection<sports> sports { get; set; } = new List<sports>();
    }
}
