// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entites.Table;

public partial class team_coach
{
    public int id { get; set; }

    public int? region_id { get; set; }

    public int? sport_sub_category_id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public virtual regional_teams region { get; set; }

    public virtual sport_sub_categories sport_sub_category { get; set; }
}