// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Server.Palaro2026.Entites.Table;
using Server.Palaro2026.Entites.View;
using Server.Palaro2026.Entities.View;

namespace Server.Palaro2026.Context;

public partial class palaro_2026Context : DbContext
{
    public palaro_2026Context(DbContextOptions<palaro_2026Context> options)
        : base(options)
    {
    }

    public virtual DbSet<billeting_quarters> billeting_quarters { get; set; }
    public virtual DbSet<divisions> divisions { get; set; }
    public virtual DbSet<events> events { get; set; }
    public virtual DbSet<gender_categories> gender_categories { get; set; }
    public virtual DbSet<levels> levels { get; set; }
    public virtual DbSet<news> news { get; set; }
    public virtual DbSet<player_profiles> player_profiles { get; set; }
    public virtual DbSet<regional_teams> regional_teams { get; set; }
    public virtual DbSet<schools> schools { get; set; }
    public virtual DbSet<sport_sub_categories> sport_sub_categories { get; set; }
    public virtual DbSet<sports> sports { get; set; }
    public virtual DbSet<sports_categories> sports_categories { get; set; }
    public virtual DbSet<team_coach> team_coach { get; set; }
    public virtual DbSet<venues> venues { get; set; }
    public virtual DbSet<vw_player_profile> vw_player_profile { get; set; }
    public virtual DbSet<vw_regional_teams> vw_regional_teams { get; set; }
    public virtual DbSet<vw_sports> vw_sports { get; set; }
    public virtual DbSet<vw_venues> vw_venues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<billeting_quarters>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__billetin__3213E83F62A22D2C");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e._long)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("long");
            entity.Property(e => e.contact_person)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.contact_person_number)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.lat).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.school_address)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.school_images)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.school_name)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.regional_team).WithMany(p => p.billeting_quarters)
                .HasForeignKey(d => d.regional_team_id)
                .HasConstraintName("FK__billeting__regio__5DCAEF64");
        });

        modelBuilder.Entity<divisions>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__division__3213E83F3FCEF1AC");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.division_name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.region).WithMany(p => p.divisions)
                .HasForeignKey(d => d.region_id)
                .HasConstraintName("FK__divisions__regio__59FA5E80");
        });

        modelBuilder.Entity<events>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__events__3213E83F7F467A0E");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.event_title)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.schedule).HasColumnType("datetime");
            entity.Property(e => e.stream_url).IsUnicode(false);

            entity.HasOne(d => d.regional_team_a).WithMany(p => p.eventsregional_team_a)
                .HasForeignKey(d => d.regional_team_a_id)
                .HasConstraintName("FK__events__regional__5441852A");

            entity.HasOne(d => d.regional_team_b).WithMany(p => p.eventsregional_team_b)
                .HasForeignKey(d => d.regional_team_b_id)
                .HasConstraintName("FK__events__regional__5535A963");

            entity.HasOne(d => d.sport_sub_category).WithMany(p => p.events)
                .HasForeignKey(d => d.sport_sub_category_id)
                .HasConstraintName("FK_events_sport_sub_categories");

            entity.HasOne(d => d.venue).WithMany(p => p.events)
                .HasForeignKey(d => d.venue_id)
                .HasConstraintName("FK__events__venue_id__571DF1D5");
        });

        modelBuilder.Entity<gender_categories>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__gender_c__3213E83F044E3BF6");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.gender_category)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<levels>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__levels__3213E83FCB3B3A16");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.level)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<news>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__news__3213E83FEF2B1E99");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.facebook_link).IsUnicode(false);
        });

        modelBuilder.Entity<player_profiles>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__player_p__3213E83FFF10F18F");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.first_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.last_name)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.school).WithMany(p => p.player_profiles)
                .HasForeignKey(d => d.school_id)
                .HasConstraintName("FK__player_pr__schoo__5BE2A6F2");

            entity.HasOne(d => d.sport_sub_category).WithMany(p => p.player_profiles)
                .HasForeignKey(d => d.sport_sub_category_id)
                .HasConstraintName("FK__player_pr__sport__5CD6CB2B");
        });

        modelBuilder.Entity<regional_teams>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__regional__3213E83F4A476762");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.regional_team_name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.regional_team_name_abbreviation)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<schools>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__schools__3213E83F5F3D2A93");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.school_name)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.division).WithMany(p => p.schools)
                .HasForeignKey(d => d.division_id)
                .HasConstraintName("FK__schools__divisio__5AEE82B9");
        });

        modelBuilder.Entity<sport_sub_categories>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__sport_su__3213E83F92479A7A");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.sub_category)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.gender_category).WithMany(p => p.sport_sub_categories)
                .HasForeignKey(d => d.gender_category_id)
                .HasConstraintName("FK__sport_sub__gende__52593CB8");

            entity.HasOne(d => d.level).WithMany(p => p.sport_sub_categories)
                .HasForeignKey(d => d.level_id)
                .HasConstraintName("FK__sport_sub__level__534D60F1");

            entity.HasOne(d => d.sport).WithMany(p => p.sport_sub_categories)
                .HasForeignKey(d => d.sport_id)
                .HasConstraintName("FK__sport_sub__sport__5165187F");
        });

        modelBuilder.Entity<sports>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__sports__3213E83FE4966238");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.sport)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.description).IsUnicode(false);

            entity.HasOne(d => d.sports_category).WithMany(p => p.sports)
                .HasForeignKey(d => d.sports_category_id)
                .HasConstraintName("FK__sports__sports_c__5070F446");
        });

        modelBuilder.Entity<sports_categories>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__sports_c__3213E83FDDC09313");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.category)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<team_coach>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__team_coa__3213E83F00EBED6A");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.first_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.last_name)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.region).WithMany(p => p.team_coach)
                .HasForeignKey(d => d.region_id)
                .HasConstraintName("FK__team_coac__regio__5812160E");

            entity.HasOne(d => d.sport_sub_category).WithMany(p => p.team_coach)
                .HasForeignKey(d => d.sport_sub_category_id)
                .HasConstraintName("FK__team_coac__sport__59063A47");
        });

        modelBuilder.Entity<venues>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__venues__3213E83FBE8947FD");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.latitude).HasColumnType("decimal(8, 6)");
            entity.Property(e => e.location)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.longitude).HasColumnType("decimal(9, 6)");
        });

        modelBuilder.Entity<vw_player_profile>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_player_profile");

            entity.Property(e => e.category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.division_name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.first_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.gender_category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.last_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.level)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.regional_team_name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.school_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.sport)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.sub_category)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_regional_teams>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_regional_teams");

            entity.Property(e => e.division_name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.school_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.regional_team_name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.regional_team_name_abbreviation)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_sports>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_sports");

            entity.Property(e => e.category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.gender_category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.level)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.sport)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.sub_category)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_sports_with_sub_categories>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_sports_with_sub_categories");

            entity.Property(e => e.category)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.sport)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.sub_category)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<vw_venues>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_venues");

            entity.Property(e => e.latitude).HasColumnType("decimal(8, 6)");
            entity.Property(e => e.location)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.longitude).HasColumnType("decimal(9, 6)");
        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}