// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class BilletingQuartersDetails
{
    public string? Region { get; set; }

    public string? Abbreviation { get; set; }

    public string? BilletingQuarter { get; set; }

    public string? Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string? ContactPerson { get; set; }

    public string? ContactPersonNumber { get; set; }
}