// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class billeting_quarters
{
    public int id { get; set; }

    public int? regional_team_id { get; set; }

    public string? school_name { get; set; }

    public string? school_address { get; set; }

    public decimal? latitude { get; set; }

    public decimal? longitude { get; set; }

    public string? contact_person { get; set; }

    public string? contact_person_number { get; set; }

    public virtual regional_teams? regional_team { get; set; }
}