// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Divisions
{
    public int ID { get; set; }

    public string? Division { get; set; }

    public int? RegionID { get; set; }

    public virtual Regions? Region { get; set; }

    public virtual ICollection<Schools> Schools { get; set; } = new List<Schools>();
}