// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class EventDetails
{
    public string? Category { get; set; }

    public string? Sport { get; set; }

    public string? Level { get; set; }

    public string? Gender { get; set; }

    public string? SubCategory { get; set; }

    public string? Venue { get; set; }

    public string? EventTitle { get; set; }

    public DateTime? Date { get; set; }

    public TimeSpan? Time { get; set; }

    public bool? OnStream { get; set; }

    public string? StreamURL { get; set; }

    public bool? IsFinished { get; set; }

    public byte[]? Attachement { get; set; }

    public bool? Archived { get; set; }

    public bool? Deleted { get; set; }

    public string? Region { get; set; }

    public string? Abbreviation { get; set; }

    public int? Score { get; set; }
}