// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Events
{
    public int ID { get; set; }

    public int? RegionalTeamAID { get; set; }

    public int? TeamAFinalScore { get; set; }

    public int? RegionalTeamBID { get; set; }

    public int? TeamBFinalScore { get; set; }

    public int? SportSubCategoryID { get; set; }

    public int? venueID { get; set; }

    public string? EventTitle { get; set; }

    public DateTime? Date { get; set; }

    public TimeSpan? Time { get; set; }

    public bool? OnStream { get; set; }

    public string? StreamURL { get; set; }

    public bool? IsFinished { get; set; }

    public int? LoserID { get; set; }

    public int? WinnerID { get; set; }

    public byte[]? Attachement { get; set; }

    public bool? Archived { get; set; }

    public bool? Deleted { get; set; }

    public virtual RegionalTeams? Loser { get; set; }

    public virtual RegionalTeams? RegionalTeamA { get; set; }

    public virtual RegionalTeams? RegionalTeamB { get; set; }

    public virtual SportSubCategories? SportSubCategory { get; set; }

    public virtual RegionalTeams? Winner { get; set; }

    public virtual Venues? venue { get; set; }
}