// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class EventVersus
{
    public int ID { get; set; }

    public int? Score { get; set; }

    public int? RegionID { get; set; }

    public int? EventID { get; set; }

    public virtual Events? Event { get; set; }

    public virtual Regions? Region { get; set; }
}