// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class EventStreams
{
    public int ID { get; set; }

    public string? StreamService { get; set; }

    public string? StreamURL { get; set; }

    public virtual ICollection<Events> Events { get; set; } = new List<Events>();
}