// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class GenderCategories
{
    public int ID { get; set; }

    public string? Gender { get; set; }

    public virtual ICollection<SportSubcategories> SportSubcategories { get; set; } = new List<SportSubcategories>();
}