// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class PlayerProfileDetails
{
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? Region { get; set; }

    public string? Abbreviation { get; set; }

    public string? Division { get; set; }

    public string? School { get; set; }

    public string? Category { get; set; }

    public string? Sport { get; set; }

    public string? Description { get; set; }

    public string? Level { get; set; }

    public string? Gender { get; set; }

    public string? SubCategory { get; set; }
}