// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class ProfilePlayerSports
{
    public int ID { get; set; }

    public int ProfilePlayerID { get; set; }

    public int? ProfilePlayerSportCoachID { get; set; }

    public int? SportSubcategoryID { get; set; }

    public virtual ProfilePlayers ProfilePlayer { get; set; } = null!;

    public virtual ProfilePlayerSportCoaches? ProfilePlayerSportCoach { get; set; }

    public virtual SportSubcategories? SportSubcategory { get; set; }
}