// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class RegionalTeams
{
    public int ID { get; set; }

    public string? RegionalTeamName { get; set; }

    public string? RegionalTeamNameAbbreviation { get; set; }

    public virtual ICollection<BilletingQuarters> BilletingQuarters { get; set; } = new List<BilletingQuarters>();

    public virtual ICollection<Divisions> Divisions { get; set; } = new List<Divisions>();

    public virtual ICollection<Events> EventsRegionalTeamA { get; set; } = new List<Events>();

    public virtual ICollection<Events> EventsRegionalTeamB { get; set; } = new List<Events>();

    public virtual ICollection<TeamCoach> TeamCoach { get; set; } = new List<TeamCoach>();
}