// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Regions
{
    public int ID { get; set; }

    public string? Region { get; set; }

    public string? Abbreviation { get; set; }

    public virtual ICollection<BilletingQuarters> BilletingQuarters { get; set; } = new List<BilletingQuarters>();

    public virtual ICollection<Divisions> Divisions { get; set; } = new List<Divisions>();

    public virtual ICollection<EventVersus> EventVersus { get; set; } = new List<EventVersus>();

    public virtual ICollection<TeamCoaches> TeamCoaches { get; set; } = new List<TeamCoaches>();
}