// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Roles
{
    public int ID { get; set; }

    public string? Role { get; set; }

    public string? RoleDescription { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}