// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class roles
{
    public int id { get; set; }

    public string? role { get; set; }

    public string? role_description { get; set; }

    public virtual ICollection<users> users { get; set; } = new List<users>();
}