// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class SchoolBilletingQuarters
{
    public int ID { get; set; }

    public int? SchoolRegionID { get; set; }

    public string? BilletingQuarter { get; set; }

    public string? Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string? ContactPerson { get; set; }

    public string? ContactPersonNumber { get; set; }

    public virtual SchoolRegions? SchoolRegion { get; set; }
}