// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class SchoolDetails
{
    public string? School { get; set; }

    public string? Division { get; set; }

    public string? Region { get; set; }

    public string? Abbreviation { get; set; }
}