// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Schools
{
    public int ID { get; set; }

    public string? SchoolName { get; set; }

    public int? DivisionID { get; set; }

    public virtual Divisions? Division { get; set; }

    public virtual ICollection<PlayerProfiles> PlayerProfiles { get; set; } = new List<PlayerProfiles>();
}