// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class SessionDetails
{
    public string ID { get; set; } = null!;

    public string? SessionID { get; set; }

    public string? RecentIP { get; set; }
}