// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class Sports
{
    public int ID { get; set; }

    public string? Sport { get; set; }

    public string? Description { get; set; }

    public int? SportsCategoryID { get; set; }

    public virtual ICollection<SportSubCategories> SportSubCategories { get; set; } = new List<SportSubCategories>();

    public virtual SportCategories? SportsCategory { get; set; }
}