// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class SportSubCategories
{
    public int ID { get; set; }

    public string? SubCategory { get; set; }

    public int? SportID { get; set; }

    public int? GenderCategoryID { get; set; }

    public int? LevelID { get; set; }

    public virtual ICollection<Events> Events { get; set; } = new List<Events>();

    public virtual GenderCategories? GenderCategory { get; set; }

    public virtual Levels? Level { get; set; }

    public virtual ICollection<PlayerProfiles> PlayerProfiles { get; set; } = new List<PlayerProfiles>();

    public virtual Sports? Sport { get; set; }

    public virtual ICollection<TeamCoach> TeamCoach { get; set; } = new List<TeamCoach>();
}