// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class sport_categories
{
    public int id { get; set; }

    public string? category { get; set; }

    public virtual ICollection<sports> sports { get; set; } = new List<sports>();
}