// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class SportDetails
{
    public string? Category { get; set; }

    public string? Sport { get; set; }

    public string? Description { get; set; }

    public string? Level { get; set; }

    public string? Gender { get; set; }

    public string? SubCategory { get; set; }
}