// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class StreamServices
{
    public int ID { get; set; }

    public string? StreamService { get; set; }

    public virtual ICollection<StreamURLs> StreamURLs { get; set; } = new List<StreamURLs>();
}