// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class StreamDetails
{
    public int StreamServiceID { get; set; }

    public string? StreamService { get; set; }

    public int StreamURLID { get; set; }

    public DateTime? Date { get; set; }

    public string? StreamURL { get; set; }

    public bool? IsFinished { get; set; }
}