// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class StreamURLs
{
    public int ID { get; set; }

    public int StreamServiceID { get; set; }

    public DateTime? Date { get; set; }

    public string? StreamURL { get; set; }

    public bool? IsFinished { get; set; }

    public virtual ICollection<Events> Events { get; set; } = new List<Events>();

    public virtual StreamServices StreamService { get; set; } = null!;
}