// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class TeamPlayerProfiles
{
    public int ID { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public int? SchoolID { get; set; }

    public int? SportSubcategoryID { get; set; }

    public virtual Schools? School { get; set; }

    public virtual SportSubcategories? SportSubcategory { get; set; }
}