// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class users
{
    public int ID { get; set; }

    public string? user_name { get; set; }

    public string? email { get; set; }

    public string? password_hash { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public DateTime? last_login { get; set; }

    public bool? active { get; set; }

    public int? role_id { get; set; }

    public virtual roles? role { get; set; }
}