// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Server.Palaro2026.Entities;

public partial class venues
{
    public int id { get; set; }

    public string? location { get; set; }

    public decimal? latitude { get; set; }

    public decimal? longitude { get; set; }

    public virtual ICollection<events> events { get; set; } = new List<events>();
}